name: app_avaliacao_ifma
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen: ^1.2.0
  charts_flutter: ^0.8.1
  webview_flutter: ^0.3.19+5
  url_launcher:  ^5.4.1
  pie_chart: ^3.1.1
  flutter_local_notifications: ^1.1.2
  path_provider: ^1.6.5
  path: ^1.6.4
  sqflite: ^1.2.0
  firebase_database: ^3.1.3
  introduction_screen: ^1.0.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/gifs/
    - assets/imgs/
    - assets/ifma/
    - assets/professores/
    - assets/users/
   
    
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/fonts/Nunito.ttf
#AB:90:72:B6:AE:BD:5E:EC:85:55:3D:34:17:F9:41:EC:2B:A0:2D:0B