name: app_avaliacao_ifma
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  splashscreen: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart parimport 'dart:math';t of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  
  assets:
    - assets/logo.png
    
    - assets/img1.png
    - assets/img2.png
    - assets/img3.png
    - assets/img4.png
    - assets/img5.png
    - assets/img6.png
    - assets/img7.png
    - assets/img8.png
    - assets/img9.png
    - assets/img10.png
    - assets/img11.png
    - assets/img12.png
    - assets/img13.png
    - assets/img14.png
    - assets/img15.png
    - assets/img16.png
    - assets/img17.png
    - assets/img18.png
    - assets/img19.png
    - assets/img20.png
    - assets/img21.png
    - assets/img22.png
    - assets/img23.png
    - assets/img24.png
    - assets/img25.png
    - assets/img26.png
    - assets/img27.png
    - assets/img28.png
    - assets/img29.png
    - assets/img30.png

    - assets/adimim.png




    
    
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf
