List perguntas = [
  'O programa da disciplina foi apresentado pelo(a) professor(a) (objetivos, conteúdo a ser desenvolvido e bibliografia).',
  'O(a) professor(a) cumpriu o programa da disciplina apresentado durante o período letivo.',
  'O(a) professor(a) demonstra domínio sobre o conteúdo apresentado, tratando-o com clareza e objetividade.',
  'O(a) professor(a) estabelece relações entre os conteúdos da sua disciplina com os conteúdos das demais disciplinas, contribuindo com a formação profissional.',
  'O(a) professor(a) comparece às aulas e cumpre os horários de início e de término das mesmas.',
  'Quando solicitado(a), o(a) professor(a) mostra-se disponível para tirar dúvidas (em sala ou em horário pedagógico) sobre a disciplina e o conteúdo ministrado',
  'O(a) professor(a) utiliza metodologia (formas de ensino) que facilite a aprendizagem.',
  'O(a) professor(a) utiliza os recursos didáticos disponíveis no IFMA Campus Caxias (laboratórios, projetor de imagem e vídeo etc), facilitando a aprendizagem.',
  'O(a) professor(a) estimula a utilização de materiais complementares (livros, sites, periódicos on-line, áudio, vídeos, entre outros).',
  'O(a) professor(a) elabora avaliações compatíveis com os conteúdos ministrados em aula.',
  'Após as avaliações, o(a) professor(a) discute as questões e esclarece a nota atribuída.',
  'O(a) professor(a) ouve opiniões e sugestões referentes às suas aulas, mostrando-se aberto(a) ao diálogo.',
  'O(a) professor(a) apresenta uma postura de respeito mútuo, preservando a imagem da Instituição, dos colegas, e dos acadêmicos.',
  'Como discente, eu me comprometi com as atividades propostas pelo(a) professor(a) que acabei de avaliar (fui assíduo nas aulas, respeitei os horários de aula chegando e saindo nos horários previstos, dediquei-me aos exercícios, trabalhos, provas e debates propostos pelo(a) professor(a) em aula).',
];
List professores = [
  'CARLOS JARDEL ARAUJO SOARES',
  'FERNANDO AMARO FERREIRA DOS SANTOS',
  'CARLOS EDUARDO FERREIRA SOARES',
  'LUIS FERNANDO MAIA SANTOS SILVA',
  'JOALDO DA SILVA LOPES',
  'VANDA MARINHA SILVA GOMES',
  'REGIA MARIA REIS GUALTER',
  'ANTONIO CARLOS GARCEZ DE SOUSA',
  'IRAMAR BATISTA DA SILVA',
  'VALDONE MENDES VIEIRA',
  'ELCIO BASILIO PEREIRA MACHADO',
  'LEUDJANE MICHELLE VIEGAS DINIZ PORTO',
  'DEBORA LAIANNY CARDOSO SOARES',
  'LETICIA DOS SANTOS ROCHA',
  'BRENO CAETANO DA SILVA',
  'FRANCISCA DA SILVA CRUZ',
  'FERNANDO DA COSTA GOMES',
  'HELLEN MARIA DE OLIVEIRA LOPES',
  'SEBASTIAO RICARDO COSTA RODRIGUES',
  'JACKLADY DUTRA NASCIMENTO',
  'KEDMAN JESUS SILVA',
  'PAULO SERGIO DA SILVA MORAES',
  'RONILSON PINHEIRO DA SILVA',
  'ACIEL TAVARES RIBEIRO',
  'JORGE LUIS DA ROCHA LIMA',
  'THAYS CRISTINNE CAMPOS LAVRA',
  'CARLOS DENILSON COIMBRA SOARES',
  'LEONARDO JOSE BRANDAO LIMA DE MATOS',
  'CLAUCYANNE MENDES VIEIRA',
  'ANTONIA DA SILVA RIBEIRO GONCALVES NETA',
  'GILSON AMORIM CESAR FILHO',
  'JONIERY RUBIM DE SOUZA',
  'VANESSA XAVIER SILVA SOUSA',
];
